import { useState } from 'react';
import type { Draft,Store } from '../engine/types';
import { calculate,close } from '../engine/math';
import { generateVerified,templates } from '../engine/bank';
import { download } from '../engine/storage';
const blank=():Draft=>({id:crypto.randomUUID(),question:'',options:['','','','',''],correctAnswer:0,expression:'',explanation:'',category:'자체 제작',difficulty:'medium',status:'draft',reviewed:false});
export default function Admin({store,update,notify}:{store:Store;update:(s:Store)=>void;notify:(s:string)=>void}){
 const [draft,setDraft]=useState<Draft>(blank()),[status,setStatus]=useState('');
 const patch=(p:Partial<Draft>)=>setDraft({...draft,...p,status:'draft',reviewed:false});
 function verify(){try{const answer=calculate(draft.expression),opts=draft.options.map(calculate);if(!draft.question.trim()||!draft.explanation.trim()||opts.some((v,i)=>opts.slice(0,i).some(x=>close(v,x)))||!close(opts[draft.correctAnswer],answer)||opts.filter(v=>close(v,answer)).length!==1)throw Error('문장·해설·선지·정답을 확인하세요.');setDraft({...draft,status:'verified'});setStatus('수식과 선지 검사 통과. 자연어 조건과 해설은 사람이 검토해야 합니다.');}catch(e){setStatus((e as Error).message);}}
 function save(){update({...store,drafts:[...store.drafts.filter(d=>d.id!==draft.id),draft]});notify('초안을 저장했습니다. 생성기 등록·독립 검산·PR 승인 전에는 학습 화면에 출제되지 않습니다.');}
 return <><div className="page-heading"><span className="eyebrow">LOCAL ADMIN · 개발 환경 전용</span><h1>문항 검토실</h1><p>초안은 승인해도 생성기에 자동 편입되지 않습니다. 독립 검산과 코드 검토를 거쳐 배포하세요.</p></div><section className="panel content-panel admin-form"><h2>문항 추가·수정</h2><label>문제<textarea value={draft.question} onChange={e=>patch({question:e.target.value})}/></label><label>유형<input value={draft.category} onChange={e=>patch({category:e.target.value})}/></label><label>난도<select value={draft.difficulty} onChange={e=>patch({difficulty:e.target.value as Draft['difficulty']})}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><label>5개 숫자 선지 (분수 가능)</label>{draft.options.map((v,i)=><div className="form-row" key={i}><input type="radio" aria-label={`${i+1}번 정답 설정`} checked={draft.correctAnswer===i} onChange={()=>patch({correctAnswer:i})}/><input value={v} aria-label={`${i+1}번 선지`} onChange={e=>patch({options:draft.options.map((x,j)=>j===i?e.target.value:x)})}/></div>)}<label>정답 계산식<input value={draft.expression} onChange={e=>patch({expression:e.target.value})}/></label><label>해설<textarea value={draft.explanation} onChange={e=>patch({explanation:e.target.value})}/></label><div className="action-row"><button onClick={verify}>자동 수식 검사</button><button onClick={save}>초안 저장</button></div><p role="status">{status}</p>{draft.status!=='draft'&&<><label className="check"><input type="checkbox" checked={draft.reviewed} onChange={e=>setDraft({...draft,reviewed:e.target.checked})}/> 문장 조건·유일성·해설을 직접 검토했습니다.</label><button disabled={!draft.reviewed} onClick={()=>{setDraft({...draft,status:'approved'});setStatus('검토 승인됨. 생성기·독립 검산·테스트·PR 승인 단계가 남아 있습니다.');}}>검토 승인</button></>}</section><section className="panel content-panel"><h2>저장한 초안</h2>{store.drafts.map(d=><div className="bank-row" key={d.id}><span>{d.question.slice(0,50)} · {d.status}</span><button onClick={()=>setDraft(d)}>수정</button><button onClick={()=>update({...store,drafts:store.drafts.filter(x=>x.id!==d.id)})}>삭제</button></div>)}<button onClick={()=>download('skct-drafts.json',JSON.stringify(store.drafts,null,2))}>초안 내보내기</button></section><section className="panel content-panel"><h2>문제은행 자동 검증</h2><button onClick={()=>{let n=0;try{for(const t of templates)for(let i=1;i<=5;i++){generateVerified(t,i*101);n++;}setStatus(`${n}문항 런타임 검사 통과. 전체 검사는 npm test로 실행하세요.`);}catch(e){setStatus(String(e));}}}>전체 유형 5시드 검사</button></section><section className="panel content-panel"><h2>신고 검토</h2>{store.reports.map(r=><div className="report-row" key={r.id}><b>{r.reason}</b><p>{r.detail}</p><code>{r.question.id} · 시드 {r.question.seed} · v{r.question.generatorVersion}</code><button disabled={r.resolved} onClick={()=>update({...store,reports:store.reports.map(v=>v.id===r.id?{...v,resolved:true}:v)})}>{r.resolved?'검토 완료':'검토 완료 표시'}</button></div>)}</section></>;
}
