import type { Store } from '../engine/types';
import { getStats,calendarDay } from '../engine/session';
import { templateById } from '../engine/bank';
export function Stats({store}:{store:Store}) {
 const stats=getStats(store.attempts), days=new Map<string,number>();
 for(const a of stats.first){const d=calendarDay(a.at);days.set(d,(days.get(d)||0)+1);}
 const entries=[...days].sort().slice(-14),max=Math.max(1,...entries.map(x=>x[1]));const results=store.results.filter(r=>!r.assisted).slice(-10);
 const series=results.map((r,i)=>`${20+i*560/Math.max(1,results.length-1)},${150-r.score/r.count*120}`).join(' ');
 return <><div className="page-heading"><span className="eyebrow">MY LEARNING</span><h1>숫자로 보는 나의 실전 감각</h1><p>첫 시도 성적을 기준으로 분석합니다. 재도전은 따로 집계합니다. 풀이를 본 뒤 답한 {stats.assisted.length}개 문항은 정답률에서 제외합니다.</p></div><div className="metrics"><div className="panel"><small>첫 시도 문항</small><strong>{stats.first.length}<em>문항</em></strong></div><div className="panel"><small>첫 시도 정답률</small><strong>{Math.round(stats.accuracy)}<em>%</em></strong></div><div className="panel"><small>평균 풀이시간</small><strong>{Math.round(stats.average)}<em>초</em></strong></div><div className="panel"><small>재도전 정답률 · {stats.retry.length}문항</small><strong>{stats.retry.length?Math.round(stats.retry.filter(a=>a.correct).length/stats.retry.length*100):0}<em>%</em></strong></div></div><div className="stats-grid"><section className="panel content-panel"><h2>유형별 정답률</h2><p className="muted">낮은 정답률부터 표시합니다.</p>{stats.groups.length?stats.groups.map(g=><div className="bar-row" key={g.subtype}><div><span>{templateById(g.subtype)?.name||g.subtype}</span><small>{g.total}문항 · 평균 {Math.round(g.seconds)}초</small></div><div className="bar-track"><i style={{width:`${g.accuracy}%`}}/></div><b>{Math.round(g.accuracy)}%</b></div>):<div className="empty">첫 문제를 풀면 취약 유형을 분석할 수 있어요.</div>}</section><div><section className="panel content-panel"><h2>최근 모의고사 점수</h2>{results.length?<><svg role="img" aria-label="최근 모의고사 정답률 추이" viewBox="0 0 600 180"><path d="M20 30H580 M20 90H580 M20 150H580" className="chart-grid"/><polyline points={series} fill="none" stroke="var(--blue)" strokeWidth="3"/>{results.map((r,i)=><circle key={r.id} cx={20+i*560/Math.max(1,results.length-1)} cy={150-r.score/r.count*120} r="5" fill="var(--blue)"><title>{calendarDay(r.at)}: {r.score}/{r.count}</title></circle>)}</svg><div className="result-list">{results.map(r=><div key={r.id}><span>{calendarDay(r.at)} · {r.area==='creative'?'창의수리':'수열추리'}</span><b>{r.score}/{r.count}</b></div>)}</div></>:<div className="empty">시험을 제출하면 성적 변화를 표시합니다.</div>}</section><section className="panel content-panel"><h2>날짜별 학습량</h2><div className="daily-chart" role="img" aria-label="최근 14개 학습일 문항 수">{entries.length?entries.map(([day,n])=><div key={day}><b>{n}</b><i style={{height:`${n/max*110}px`}}/><small>{day.slice(5)}</small></div>):<div className="empty">아직 학습 기록이 없습니다.</div>}</div></section><section className="panel content-panel"><h2>영역별 정답률</h2>{(['creative','sequence'] as const).map(area=>{const a=stats.first.filter(a=>a.question.type===area);return <div className="result-list" key={area}><div><span>{area==='creative'?'창의수리':'수열추리'} · {a.length}문항</span><b>{a.length?Math.round(a.filter(x=>x.correct).length/a.length*100):0}%</b></div></div>;})}</section></div></div></>;
}
